export default {
  LOAD_RECIPES: 'LOAD_RECIPES',
  LOAD_RECIPES_ERROR: 'LOAD_RECIPES_ERROR',
  LOAD_RECIPE: 'LOAD_RECIPE',
  LOAD_RECIPE_ERROR: 'LOAD_RECIPE_ERROR',
  LOAD_LISTS: 'LOAD_LISTS',
  LOAD_LISTS_ERROR: 'LOAD_LISTS_ERROR',
  UPDATE_LIST: 'UPDATE_LIST',
  UPDATE_LIST_ERROR: 'UPDATE_LIST_ERROR',
};
